language: node_js
node_js:
  - "7"
  - "10"
cache: yarn
script:
  - yarn test
branches:
  only:
    - master
    - /^greenkeeper/.*$/
notifications:
  slack: in2:t4HfbJOtRL7uekgIPh2DUIKb
  email: false
